version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - npm install
      - npm run webpack

artifacts:
  files:
    - files/*
    - images/*
    - styles/*
    - favicon.ico
    - index.html
    - dist/bundle.js
