version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  build:
    commands:
      - echo Nothing to do yet

artifacts:
  files:
    - files/*
    - images/*
    - styles/*
    - favicon.ico
    - index.html
